import turtle as tur

def drawStar (colour, pen, x, y):
    tur.fillcolor(colour)
    tur.pencolor(pen)
    tur.penup()
    tur.goto(x, y)
    tur.pendown()
    tur.width(2)
    tur.begin_fill()
    for i in range(5):
        tur.forward(100)
        tur.right(144)
    tur.end_fill()

def drawRose(colour, pen, x, y):
    tur.fillcolor(colour)
    tur.pencolor(pen)
    tur.penup()
    tur.goto(x, y)
    tur.pendown()
    tur.width(2)
    tur.begin_fill()
    tur.setheading(0)
    tur.circle(10, 180)
    tur.circle(25, 110)
    tur.left(50)
    tur.circle(60, 45)
    tur.circle(20, 170)
    tur.right(24)
    tur.fd(30)
    tur.left(10)
    tur.circle(30, 110)
    tur.fd(20)
    tur.left(40)
    tur.circle(90, 70)
    tur.circle(30, 150)
    tur.right(30)
    tur.fd(15)
    tur.circle(80, 90)
    tur.left(15)
    tur.fd(45)
    tur.right(165)
    tur.fd(20)
    tur.left(155)
    tur.circle(150, 80)
    tur.left(50)
    tur.circle(150, 90)
    tur.end_fill()

    tur.left(150)
    tur.circle(-90, 70)
    tur.left(20)
    tur.circle(75, 105)
    tur.setheading(60)
    tur.circle(80, 98)
    tur.circle(-90, 40)

    tur.left(180)
    tur.circle(90, 40)
    tur.circle(-80, 98)
    tur.setheading(-83)

    tur.fd(30)
    tur.left(90)
    tur.fd(25)
    tur.left(45)
    tur.fillcolor("dark green")
    tur.begin_fill()
    tur.circle(-80, 90)
    tur.right(90)
    tur.circle(-80, 90)
    tur.end_fill()
    tur.right(135)
    tur.fd(60)
    tur.left(180)
    tur.fd(85)
    tur.left(90)
    tur.fd(80)

    tur.right(90)
    tur.right(45)
    tur.fillcolor("dark green")
    tur.begin_fill()
    tur.circle(80, 90)
    tur.left(90)
    tur.circle(80, 90)
    tur.end_fill()
    tur.left(135)
    tur.fd(60)
    tur.left(180)
    tur.fd(60)
    tur.right(90)
    tur.circle(200, 60)


def drawDaisy(colour, pen, x, y):
    tur.pencolor(pen)
    tur.penup()
    tur.goto(x, y)
    tur.pendown()
    tur.width(2)
    tur.begin_fill()
    tur.fillcolor("white")
    for i in range(6):
        tur.setheading(60 * i)
        tur.circle(10, 210)
    tur.end_fill()

    tur.penup()
    tur.left(90)
    tur.fd(2)
    tur.right(90)
    tur.fd(10)
    tur.pendown()
    tur.right(90)

    tur.begin_fill()
    tur.fillcolor(colour)
    tur.setheading(80)
    tur.circle(10, 361)
    tur.end_fill()
    tur.setheading(0)

    tur.penup()
    tur.right(90)
    tur.fd(2)
    tur.left(90)
    tur.fd(10)
    tur.pendown()
    tur.right(90)

    tur.setheading(300)
    tur.circle(-80, 70)

    tur.begin_fill()
    tur.fillcolor("green")
    tur.setheading(60)
    tur.circle(20, 90)
    tur.left(90)
    tur.circle(20, 90)
    tur.end_fill()


def drawTulip(colour, pen, x, y):
    tur.pencolor(pen)
    tur.penup()
    tur.goto(x, y)
    tur.pendown()
    tur.width(2)
    tur.begin_fill()
    tur.fillcolor(colour)
    tur.setheading(230)
    tur.circle(50, 265)
    for i in range(2):
        tur.left(90)
        tur.forward(26)
        tur.right(90)
        tur.forward(26)
    tur.end_fill()

    tur.penup()
    tur.setheading(0)
    tur.right(90)
    tur.fd(85)
    tur.left(90)
    tur.fd(40)
    tur.pendown()

    tur.begin_fill()
    tur.fillcolor("dark green")
    tur.setheading(270)
    tur.pencolor("dark green")
    tur.width(5)
    tur.forward(125)
    tur.width(2)
    tur.setheading(0)
    tur.circle(110, 150)
    tur.setheading(300)
    tur.circle(-150, 90)
    tur.end_fill()

def drawWindMill(base, blades, x, y):
    tur.penup()
    tur.goto(x, y)
    tur.pendown()
    tur.width(2)
    tur.begin_fill()
    tur.fillcolor(base)
    tur.pencolor(base)
    tur.setheading(0)
    tur.fd(85)
    tur.setheading(-80)
    tur.fd(250)
    tur.setheading(180)
    tur.fd(175)
    tur.setheading(80)
    tur.fd(250)
    tur.end_fill()

    tur.penup()
    tur.setheading(0)
    tur.fd(42.5)
    tur.setheading(-90)
    tur.fd(30)
    tur.pendown()

    tur.pencolor(blades)
    tur.begin_fill()
    tur.fillcolor(blades)
    for i in range(10):
        tur.forward(200)
        tur.right(120)
        tur.forward(40)
        tur.goto(x+42.5, y-30)
        tur.left(84)
    tur.end_fill()


colours = ["red", "yellow", "purple", "blue", "teal", "green", "light green", "gold", "silver", "orange",
               "dark blue", "light blue"]


images = [drawTulip, drawDaisy, drawRose, drawWindMill, drawStar]